# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_aploc.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13request_aploc.proto\x12\raploc.request\"\x96\x01\n\x0c\x41plocRequest\x12\x38\n\x0b\x64\x65vice_info\x18\x01 \x01(\x0b\x32\x1e.aploc.request.AplocDeviceInfoH\x00\x88\x01\x01\x12<\n\x10long_string_data\x18\x02 \x03(\x0b\x32\".aploc.request.AplocLongStringDataB\x0e\n\x0c_device_info\";\n\x0f\x41plocDeviceInfo\x12\x14\n\x0c\x64\x65vice_model\x18\x01 \x01(\t\x12\x12\n\nos_version\x18\x02 \x01(\t\"\xbc\x01\n\x13\x41plocLongStringData\x12\x34\n\tsub_data1\x18\x01 \x01(\x0b\x32\x1c.aploc.request.AplocSubData1H\x00\x88\x01\x01\x12.\n\x08location\x18\x02 \x03(\x0b\x32\x1c.aploc.request.AplocLocation\x12\x31\n\nbssid_info\x18\x03 \x03(\x0b\x32\x1d.aploc.request.AplocBssidInfoB\x0c\n\n_sub_data1\"\x86\x01\n\rAplocSubData1\x12\x17\n\x0funknown_varint1\x18\x01 \x01(\x03\x12\x17\n\x0funknown_varint2\x18\x02 \x01(\x05\x12\x17\n\x0funknown_varint3\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\x12\x17\n\x0funknown_varint5\x18\x05 \x01(\x05\"\xc2\x02\n\rAplocLocation\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x16\n\x0eunknown_float3\x18\x03 \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x05 \x01(\x02\x12\x16\n\x0eunknown_float6\x18\x06 \x01(\x02\x12\x11\n\ttimestamp\x18\t \x01(\x01\x12\x18\n\x10unknown_varint13\x18\r \x01(\x05\x12\x33\n\x0cinner_data18\x18\x12 \x01(\x0b\x32\x1d.aploc.request.AplocInnerData\x12\x33\n\x0cinner_data19\x18\x13 \x01(\x0b\x32\x1d.aploc.request.AplocInnerData\x12\x33\n\x0cinner_data20\x18\x14 \x01(\x0b\x32\x1d.aploc.request.AplocInnerData\">\n\x0e\x41plocInnerData\x12\x15\n\rinner_varint1\x18\x01 \x01(\x05\x12\x15\n\rinner_varint2\x18\x02 \x01(\x05\"u\n\x0e\x41plocBssidInfo\x12\r\n\x05\x62ssid\x18\x01 \x01(\t\x12\x17\n\x0fsignal_strength\x18\x02 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\x05\x12\x17\n\x0funknown_double4\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'request_aploc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APLOCREQUEST']._serialized_start=39
  _globals['_APLOCREQUEST']._serialized_end=189
  _globals['_APLOCDEVICEINFO']._serialized_start=191
  _globals['_APLOCDEVICEINFO']._serialized_end=250
  _globals['_APLOCLONGSTRINGDATA']._serialized_start=253
  _globals['_APLOCLONGSTRINGDATA']._serialized_end=441
  _globals['_APLOCSUBDATA1']._serialized_start=444
  _globals['_APLOCSUBDATA1']._serialized_end=578
  _globals['_APLOCLOCATION']._serialized_start=581
  _globals['_APLOCLOCATION']._serialized_end=903
  _globals['_APLOCINNERDATA']._serialized_start=905
  _globals['_APLOCINNERDATA']._serialized_end=967
  _globals['_APLOCBSSIDINFO']._serialized_start=969
  _globals['_APLOCBSSIDINFO']._serialized_end=1086
# @@protoc_insertion_point(module_scope)
